version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: website-analyzer
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python src/main.py --help
