# API 服務配置 (默認使用 Azure OpenAI)
api_service: "azure_openai"  # 或 "openai"

# Azure OpenAI 配置 (默認)
azure_openai:
  deployment_name: gpt-4-vision
  model: gpt-4-vision-preview
  max_tokens: 2000
  temperature: 0.1
  api_version: "2024-02-15-preview"

# OpenAI 標準 API 配置 (備選)
openai:
  model: gpt-4-vision-preview
  max_tokens: 2000
  temperature: 0.1

# 瀏覽器配置
browser:
  headless: true
  window_size: [1920, 1080]
  mobile_size: [375, 667]
  tablet_size: [768, 1024]
  timeout: 30
  wait_time: 5
  
# 分析配置
analysis:
  max_pages: 50
  screenshot_formats: [desktop, tablet, mobile]
  batch_size: 5
  retry_attempts: 3
  
# 輸出配置
output:
  formats: [html, pdf]
  include_screenshots: true
  report_title: "Website Analysis Report"
  
# 日誌配置
logging:
  level: "INFO"
  file: "logs/analyzer.log"
  max_size: "10MB"
  backup_count: 5
